### PR TITLE
Feature/configuable controller paths

### PR DESCRIPTION
**Pull request by bashleigh**
#8

### CODE REVIEW

**Comment by bashleigh** [comment]
coveralls 🖕

**Comment by adrien2p** [comment]
I think it always better to have 4 spaces as config for more readability, what do you think ?

**Comment by bashleigh** [comment]
@adrien2p yeaaaa I'm not sold on which to use. Most people argue that for javascript we should use 2 spaces. I think @fenos prefers 2 spaces? I'm a bit in between really. What do you prefer @shekohex?

**Comment by adrien2p** [comment]
Yeah i can understand but it's more about readability, at the end we should not have any problem to read a code from outside :) but i'm not stuck

**Comment by shekohex** [comment]
@adrien2p i don't have a wide screen so 4 spaces not suitable for me 😂.

I prefer flat, not nested code, 2 spaces is good though.

**Comment by adrien2p** [comment]
Okay i surrender ^^

**Comment by bashleigh** [comment]
Just ganna add a comment here and see if the slack integrations worked?

**Pull request merged**
